### ISSUE TITLE
Update Warnings in OS System 1.0.7

### ISSUE THREAD

**Issue by photodude** [OSTraining/OSSystem#4]
The following "warnings" display on checking for updates in Joomla 3.4.1 with OS System 1.0.7
```
Update: Could not open update site #18 "OSSystem", URL: https://deploy.ostraining.com/client/update/free/stable/plg_system_ossystem/extension.xml
```

**Comment by htmgarcia** [comment]
Hi @photodude 
Please try redownloading OSMap (https://www.alledia.com/extensions/osmap/) and reinstalling from Extensions > Extension manager > Uploadn and Install

See if that removes the warning

**Comment by photodude** [comment]
@htmgarcia I have redownloaded and reinstalled 3.1.1. No change in the messages.

**Comment by htmgarcia** [comment]
@photodude please post this same details in the forum https://www.alledia.com/forum/osmap, then send us an email with your backend access to support@alledia.com with the link of the forum post to take a look

**Comment by photodude** [comment]
@htmgarcia This issue seems to have resolved itself. Last check for updates did not return  the warning about not being able to open the update site.

related issues are all ready posted in the forum
https://www.alledia.com/forum/osmap/162/
https://www.alledia.com/forum/osmap/146/

Closing as this appears to be resolved
